### ISSUE TITLE
Card number and expiration validation

### ISSUE THREAD

**Issue by rtician** [AfikDeri/v-credit-card#6]
Hello,

I'm using Firefox and valid card numbers and expirations are being alert as wrong:
![image](https://user-images.githubusercontent.com/15620734/68773826-ff3f4e80-060a-11ea-9958-45dced13006d.png)

I think it's because the attribute `pattern="[0-9]*"` on the input. Chrome doesn't seem to have a problem with it.

**Comment by ci83rtda** [comment]
Hi Pattern should be like this.

`pattern="(?:0[1-9]|1[0-2])/[0-9]{2}"`

first month digit can only be either 0 or 1 then second month digit from 1 to 2 if first digit is 1 or 1 to 9 if first digit is 0.

**Comment by ci83rtda** [comment]
I created a pull request to fix the issue
#7

**Comment by gtbustos** [comment]
It seems this wasn't updated on latest version. Could you check it out? 
`<input type="text" name="card_number" pattern="[0-9]*" inputmode="numeric">`

Best!

**Comment by AfikDeri** [comment]
@gtbustos it looks like it's in the latest version, are you sure you don't see it?

**Comment by gtbustos** [comment]
`"v-credit-card": "^1.2.1",`

![image](https://user-images.githubusercontent.com/5365420/69875465-f94c9d00-129b-11ea-907c-9339705ee6ee.png)

The source code on Github is ok, I can't see it on npm package. 
I rebuilt the package and it works fine but I rather use the official version.

**Comment by rtician** [comment]
Hi @AfikDeri, any updates?

**Comment by AfikDeri** [comment]
Sorry for the delay, it should work now, try version `1.2.2`
